# Generated by Django 6.0 on 2026-04-06 21:51

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(80)])),
                ('dados_entrada', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('criado', models.DateTimeField(default=datetime.datetime(2026, 4, 6, 18, 51, 44, 818733))),
                ('atualizado', models.DateTimeField(default=datetime.datetime(2026, 4, 6, 18, 51, 44, 818733))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('descricao', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('descricao', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(5)])),
                ('url', models.URLField(null=True)),
                ('inicio', models.DateTimeField()),
                ('termino', models.DateTimeField()),
                ('freeze', models.DateTimeField()),
                ('publico', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(default=datetime.datetime(2026, 4, 6, 18, 51, 44, 850003))),
                ('atualizado', models.DateTimeField(default=datetime.datetime(2026, 4, 6, 18, 51, 44, 850003))),
                ('penalidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('compilador', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(5)])),
                ('versao', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('multiplicador_tempo', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('multiplicador_memoria', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('teste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judge.teste')),
                ('ordem', models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'abstract': False,
            },
            bases=('judge.teste',),
        ),
        migrations.CreateModel(
            name='Exemplo',
            fields=[
                ('teste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judge.teste')),
                ('peso', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
            options={
                'abstract': False,
            },
            bases=('judge.teste',),
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('titulo', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('enunciado', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('enunciado_entrada', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('enunciado_saida', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('dificuldade', models.CharField(choices=[(1, 'Muito Fácil'), (2, 'Fácil'), (3, 'Básico'), (4, 'Intermediário'), (5, 'Intermediário Alto'), (6, 'Difícil'), (7, 'Muito Difícil'), (8, 'Avançado'), (9, 'Muito Avançado'), (10, 'Perito')])),
                ('idioma', models.CharField(choices=[('PT_BR', 'Português do Brasil'), ('EN_US', 'Inglês dos EUA'), ('ES_ES', 'Espanhol da Espanha')])),
                ('fonte', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)])),
                ('limite_tempo_ms', models.CharField(choices=[(1000, '1 segundo'), (2000, '2 segundos'), (3000, '3 segundos'), (4000, '4 segundos'), (5000, '5 segundos'), (6000, '6 segundos'), (7000, '7 segundos'), (8000, '8 segundos'), (9000, '9 segundos'), (10000, '10 segundos')], default=1000)),
                ('limite_memoria_mb', models.CharField(choices=[('8', '8 MB'), ('16', '16 MB'), ('32', '32 MB'), ('64', '64 MB'), ('128', '128 MB'), ('256', '256 MB')], default='32')),
                ('publico', models.BooleanField(default=True)),
                ('nota', models.IntegerField(choices=[(100, '100'), (150, '150'), (200, '200'), (250, '250'), (300, '300'), (400, '400'), (500, '500'), (600, '600'), (800, '800'), (1000, '1000')])),
                ('criado', models.DateTimeField(default=datetime.datetime(2026, 4, 6, 18, 51, 44, 834361))),
                ('atualizado', models.DateTimeField(default=datetime.datetime(2026, 4, 6, 18, 51, 44, 834361))),
                ('categorias', models.ManyToManyField(to='judge.categoria')),
                ('testes', models.ManyToManyField(to='judge.teste')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemaCompeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('pontos', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('ordem', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.competicao')),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, related_name='judge_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='judge_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fonte', models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('status', models.TextField(choices=[('NOT_ANSWERED', 'Não Respondida'), ('IN_QUEUE', 'Em fila de execução'), ('RUNNING', 'Execução'), ('ACCEPTED', 'Aceito'), ('WRONG_ANSWER', 'Resposta Errada'), ('TIME_LIMIT_EXCEEDED', 'Tempo Limite Excedido'), ('MEMORY_LIMIT_EXCEEDED', 'Limite de Memória Excedido'), ('RUNTIME_ERROR', 'Erro de Runtime'), ('COMPILATION_ERROR', 'Erro de Compilação'), ('PRESENTATION_ERROR', 'Erro de Apresentação'), ('INTERNAL_ERROR', 'Erro Interno')])),
                ('submetido', models.DateTimeField()),
                ('avaliado_em', models.DateTimeField()),
                ('tempo_execucao_ms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('memoria_utilizada_kb', models.IntegerField(validators=[django.core.validators.MinValueValidator(32)])),
                ('nota', models.IntegerField(choices=[(100, '100'), (150, '150'), (200, '200'), (250, '250'), (300, '300'), (400, '400'), (500, '500'), (600, '600'), (800, '800'), (1000, '1000')])),
                ('log_execucao', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('linguagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.linguagem')),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2016, 4, 6))])),
                ('pais', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('genero', models.TextField(choices=[('MAN', 'Homem'), ('WOMAN', 'Mulher'), ('NON_BINARY', 'Não binário'), ('NOT_INFORMED', 'Não informado')])),
                ('pagina_pessoal', models.URLField(max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(15)])),
                ('biografia', models.TextField(null=True)),
                ('idioma', models.TextField(choices=[('PT_BR', 'Português do Brasil'), ('EN_US', 'Inglês dos EUA'), ('ES_ES', 'Espanhol da Espanha')])),
                ('premium', models.BooleanField(default=False)),
                ('membro_desde', models.DateField(default=datetime.date(2026, 4, 6))),
                ('instituicao', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3)])),
                ('posicao_ranking', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('resolvidos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('submetidos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('treinador', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='judge.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateTimeField()),
                ('oficial', models.BooleanField(default=True)),
                ('total_pontos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.competicao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
